DROP DATABASE IF EXISTS SnippetGoodTestDatabase;
CREATE DATABASE SnippetGoodTestDatabase;
USE SnippetGoodTestDatabase;

CREATE TABLE User_Data(
UserID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
Username VARCHAR(32) NOT NULL,
Passwrd VARCHAR(32) NOT NULL
);

CREATE TABLE Snippet_Data(
SnippetID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
CreatorID BIGINT,
Language VARCHAR(32),
Description TEXT NOT NULL,
FOREIGN KEY (CreatorID) REFERENCES User_Data(UserID)
);

